base: 'https://kickermanagerspiel.82.pc/'
baseVariants:
  -
    base: 'https://kickermanagerspiel.82.pc/'
    condition: 'applicationContext == "Development/dsimon"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: de
    hreflang: de
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
