services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Simon\Kickermanagerspiel\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
  Simon\Kickermanagerspiel\Command\ImportCsvCommand:
    tags:
      - name: 'console.command'
        command: 'kickermanagerspiel:import:csv'
        description: 'Import CSVs from kicker.de'
  Simon\Kickermanagerspiel\Command\CreatePerfectTeamCommand:
    tags:
      - name: 'console.command'
        command: 'kickermanagerspiel:create:perfectteam'
        description: 'Create perfect team'